version: '2'
services:
    textma-app:
        image: textma
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://textma-mysql:3306/textma?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    textma-mysql:
        extends:
            file: mysql.yml
            service: textma-mysql
